services:
    sonata.admin.post:
        class: AppBundle\Admin\SubmissionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin", label: "Selfie" }
        arguments:
            - ~
            - AppBundle\Entity\Submission
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]